### ISSUE TITLE
[Epic] Clean up Jupyterlab Extensions

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#111]
Epic to track cleaning up extensions (removing broken/unused, fixing ones that are not working, etc).  Note that this should be done by the same person or in coordination with #112 as they overlap.  More discussion in StatCan/kubeflow-containers#102.

* [x] #103 Remove Go kernel
* [x] #104 Clean up and test dash, plotly, and matplotlib extensions + build demos
* [x] #106 Pin versions of all our extensions
* [x] #108 Xeus python kernel autocomplete partly broken
* [x] #109 jupyter-lsp (backend) / jupyterlab-lsp (frontend)
* [x] #110 jupyter-widgets/jupyterlab-manager installed twice(?)
* [x] StatCan/jupyter-notebooks#29 Build a demo using Facets 
* [x] #117 Update inherited image version
