### ISSUE TITLE
S3 Download GUI for Jupyter (evenutally support Uploads too)

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#90]
I started [this](https://github.com/blairdrummond/flask-s3-viewer) and my example app is in the `example` folder. We can download files from S3 Storage into our Jupyter notebooks with it!!! 

![Screenshot from 2020-08-09 15-59-53](https://user-images.githubusercontent.com/10801138/89740736-67677780-da59-11ea-8ee5-edae6c458123.png)

# Todo

- [x] Download files from our storage system

- [ ] Test the search functionality

- [ ] Insert some attribution to the original author of [flask-s3-viewer](https://github.com/hidekuma/flask-s3-viewer). Originally there was a link in the footer, but I removed it while playing around with the buckets list. It should be re-added.

- [ ] Vault rotation: Need to somehow reload the credentials when they expire... Not sure the best solution!

- [ ] Add a shortcut on the JupyterLab front page with this https://github.com/yuvipanda/jupyter-launcher-shortcuts

- [ ] **Upload tool!** by far the trickiest here. Need some way to upload files too... Might require us to create a bit of UI.

CC @brendangadd @ca-scribner 

# Notes

I just quickly threw this together, so the code probably could be tidied up (not that I wrote much code here).

To run on kubeflow you need to muck around with weird proxy things. Take a look at [this requirements file](https://github.com/blairdrummond/flask-s3-viewer/blob/master/example/requirements.txt)

# Upstream Contribution?

I think there's potential for this to be a useful tool for others if we do it well. I couldn't find many **remote to remote** file-managers. If we can get that figured out I think this might be useful for more people.

That said, I don't think it's "Upstream" per-se, I think it just has merit as its own tool. But would be important for us to add the ability to upload files from Jupyter first.

**Comment by sylus** [comment]
Hey @blairdrummond with the recent S3 fuse mount additions is this still needed?

No worries if is just was curious.

**Comment by blairdrummond** [comment]
Nope!!! I like the S3 Fuse option much more :-)
